{% set version = "5.3.5" %}

package:
  name: lua
  version: {{ version }}

source:
  - url: http://www.lua.org/ftp/lua-{{ version }}.tar.gz
    sha256: 0c2eed3f960446e1a3e4b9a1ca2f3ff893b6ce41942cf54d5dd59ab4b3b058ac
    patches:
      # Enables Lua to look for packages on a relative path
      - luaconf.patch
      # Enables readline on linux
      - Makefile.patch
  - path: CMakeLists.txt

build:
  number: 1
  detect_binary_files_with_prefix: true

requirements:
  build:
    - {{ compiler('c') }}  # [not win]
    - vs2017_win-64  # [win64]
    - vs2017_win-32  # [win32]
    - ninja  # [win]
    - cmake  # [win]
    - sed  # [unix]
  host:
    - readline  # [not win]
    - ncurses  # [not win]
  run:
    - readline  # [not win]
    - ncurses  # [not win]

test:
  commands:
    - if not exist %LIBRARY_INC%\\lua.h exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\lua.dll exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\lua.exe exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\lua.exe exit 1  # [win]
    - lua -v
    - lua -e "print(package.path)"

about:
  home: http://www.lua.org/
  summary: Lua is a powerful, fast, lightweight, embeddable scripting language
  license: MIT
  license_file: doc/readme.html

extra:
  recipe-maintainers:
    - alexbw
    - seanyen
