{% set version = "5.4.6" %}

package:
  name: lua
  version: {{ version }}
source:
  - url: http://www.lua.org/ftp/lua-{{ version }}.tar.gz
    sha256: 7d5ea1b9cb6aa0b59ca3dde1c6adcb57ef83a1ba8e5432c0ecd06bf439b3ad88
    patches:
      # Enables Lua to look for packages on a relative path
      - luaconf.patch
      # Build as a shared library
      - liblua.so.patch
      # Enables readline on linux
      - Makefile.patch
  - path: CMakeLists.txt

build:
  number: 1
  detect_binary_files_with_prefix: true
  run_exports:
    # http://www.lua.org/versions.html#numbering
    - {{ pin_subpackage('lua', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - ninja          # [win]
    - cmake          # [win]
    - sed            # [unix]
    - make           # [unix]
  host:
    - readline  # [not win]
    - ncurses   # [not win]
  run:
    - readline  # [not win]
    - ncurses   # [not win]

test:
  commands:
    - test -f $PREFIX/lib/liblua$SHLIB_EXT  # [unix]
    - if not exist %LIBRARY_INC%\\lua.h exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\lua.dll exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\lua.exe exit 1  # [win]
    - if not exist %LIBRARY_BIN%\\lua.exe exit 1  # [win]
    - lua -v
    - lua -e "print(package.path)"

about:
  home: http://www.lua.org/
  summary: Lua is a powerful, fast, lightweight, embeddable scripting language
  license: MIT
  license_file: doc/readme.html

extra:
  recipe-maintainers:
    - anjos
    - alexbw
    - seanyen
    - izahn
