{% set version = "5.3.5" %}

package:
  name: lua
  version: {{ version }}

source:
  fn: lua-{{ version }}.tar.gz
  url: http://www.lua.org/ftp/lua-{{ version }}.tar.gz
  md5: 4f4b4f323fd3514a68e0ab3da8ce3455
  patches:
    # Enables Lua to look for packages on a relative path
    - luaconf.patch
    # Enables readline on linux
    - Makefile.patch

build:
  number: 0
  detect_binary_files_with_prefix: true
  skip: True  # [win]

requirements:
  build:
    - readline 6.2*
    - ncurses 5.9*
  run:
    - readline 6.2*
    - ncurses 5.9*

test:
  commands:
    - lua -v
    - lua -e "print(package.path)"

about:
  home: http://www.lua.org/
  summary: Lua is a powerful, fast, lightweight, embeddable scripting language
  license: MIT

extra:
  recipe-maintainers:
    - alexbw
