schema_version: 1

context:
  version: 5.1.5

package:
  name: lua
  version: ${{ version }}

source:
  - url: https://www.lua.org/ftp/lua-${{ version }}.tar.gz
    sha256: 2640fc56a795f29d28ef15e13c34a47e223960b0240e8cb0a82d9b0738695333
    patches:
      # Enables Lua to look for packages on a relative path
      # Build as a shared library
      # Enables readline on linux
      # add proper readline support, as well as proper paths for package loading
      - lua-51-conda-forge.patch

build:
  number: 4
  skip: win
  prefix_detection:
    ignore_binary_files: true

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - make
  host:
    - readline
  run:
    - readline
  run_exports:
    - ${{ pin_subpackage('lua', upper_bound='x.x') }}

tests:
  - script:
      - test -f $PREFIX/lib/liblua$SHLIB_EXT
      - lua -v
      - lua -e "print(package.path)"

about:
  summary: Lua is a powerful, fast, lightweight, embeddable scripting language
  license: MIT
  license_file: COPYRIGHT
  homepage: http://www.lua.org/

extra:
  recipe-maintainers:
    - alexbw
    - seanyen
    - izahn
    - anjos
