# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "tA0ml9JWkbSKvGdcWQ/FUtcxG9qFswaPKYtWWLguUMeHxaXaM/bMtEtJcXMLzyW8yExjV4jVczyRkRAqIdZJbIGrY2dsp+ns0mFoFSMYsn1VvtoChd8IerTAPS9HrgNfR93+kflMh9Nm3lZqx813TVBTlkmAaH5MnN69VgaPbAe+UrZiT3w/6jjG8LmijKU9YyLrN8SgLlTQdSMWGC6bMsulmjzJoz+r5yA9CR4+GIqKiDhrubRVyPKKJuNIGYw8xr4PwYdYBEpt/JiE5YBqde43/fRanOLaLAWyYk5hoFt6TWAfbUVU/53evrfpu1hga2fC4DNS+n2woK6GVln2v4e2pslz6glBLYoB3/00YB8ToAMf6fzMHDWbro9ZCITlB+E1xOZ2rb7G9zkqdx3hIF7+XJvmGfdscht4iSTcLZspl/NGKJKZswqM7QnMhr6kR+IhYheVhJMTPxi4SHttjzBPi4AIEMgNLkI0Y7BKnxyC7/qDPebfnagYkwO4ItZjEYndBQSDeLiOLXUc+JEK9SmFICPgOjcceKSzXg/oGsgrHWChpap94whXZB7VuKcozakkKr3Rg8OfledcHSlJZhyeTL+3rK2AHaIi6tiaRiLVmwIGE1E6MBS6sGuiINFRMTvY0lzyY4ITAYgmrCSbIxDHX++PVPpNhoWANpR3Y8s="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

      # install conda-build 2.x to build with a long prefix
      conda install --yes --quiet conda-build=2
      conda info

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main

  # inspect the prefix lengths of the built packages
  - conda inspect prefix-lengths /Users/travis/miniconda3/conda-bld/osx-64/*.tar.bz2
