build_platform:
  osx_arm64: osx_64
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  win_arm64: win_64
conda_forge_output_validation: true
provider:
  linux_aarch64: default
  linux_ppc64le: default
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
test: native_and_emulated
bot:
  automerge: true
  abi_migration_branches:
    - "5.1"
conda_install_tool: pixi
conda_build_tool: rattler-build
