bot:
  automerge: true
build_platform:
  osx_arm64: osx_64
  linux_aarch64: linux_64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
conda_build_tool: rattler-build
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
